version: '2'
services:
    registry_service:
        build: registry
        image: eureka/registry:2
        ports:
          - 1111:1111
    proxy_service:
        build: reverse_proxy
        image: eureka/proxy:1
        ports:
          - 4444:4444
        depends_on:
          - registry_service
        links:
          - registry_service:registry
    #auth_service:
    #    build: auth
    #    image: eureka/auth:8
    #    depends_on:
    #      - registry_service
    #    links:
    #      - registry_service:registry
    #content_service:
    #    build: content
    #    depends_on:
    #      - registry_service
    #    links:
    #      - registry_service:registry
    #      - config_service:configserver
    insecure_service:
            build: insecure
            depends_on:
              - registry_service
            links:
              - registry_service:registry
              - config_service:configserver
    #sidecar:
    #    build: sidecar
    #    image: eureka/sidecar
    #    depends_on:
    #      - registry_service
    #    links:
    #      - registry_service:registry
    config_service:
        build: config-microservice
        links:
          - registry_service:registry
        environment:
          -  SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/ricardobaumann/config-repo

