server:
  port: 8888

eureka:
  instance:
    hostname: properties
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config